name: Azure DiskInspect Build and Test
on: [pull_request]
jobs:
  Validate_Manifest_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Manifest changes
        run: ./tests/requires_doc_change.sh
        shell: bash
