name: Azure DiskInspect Manifest Validation
on: [pull_request]
jobs:
  Validate_Manifest_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate Manifest changes
        run: ./tests/requires_doc_change.sh
        shell: bash
